/* --------------------------------------------------------------------
                         Print Dialog Header File
                              Chapter 11

                    Real World Programming for OS/2
             Copyright (c) 1993 Blain, Delimon, and English
-------------------------------------------------------------------- */

#define QUEUE_INFO_DLG              100
#define SELECT_PRINTER_DLG          102
#define PRINT_DLG                   103
#define PRINT_STATUS_DLG            104
#define STATUS_WND                  105

#define DID_QUEUE_NAMES             200
#define DID_PRIORITY                201
#define DID_STATUS                  202
#define DID_NUMBER_JOBS             203
#define DID_START_TIME              204
#define DID_END_TIME                205
#define DID_DEFAULT_DEVICE          206
#define DID_PRINTERS                207
#define DID_TECHNOLOGY              208
#define DID_FORMS                   209
#define DID_FORM_CX                 210
#define DID_FORM_CY                 211
#define DID_LEFT_CLIP               212
#define DID_BOTTOM_CLIP             214
#define DID_FORM_ATTR               215
#define DID_RIGHT_CLIP              216
#define DID_TOP_CLIP                217
#define DID_CAPS_WIDTH              218
#define DID_CAPS_HEIGHT             219
#define DID_HORZ_RES                220
#define DID_VERT_RES                221
#define DID_BITBLT                  222
#define DID_BANDING                 223
#define DID_SETPEL                  224
#define DID_RASTER_FONT             225
#define DID_KERNING                 226
#define DID_PALETTE                 227
#define DID_JOBPROPS                228
#define DID_UPDATE                  229
#define DID_PRINTER                 300
#define DID_DOCUMENT                301
#define DID_COPIES                  302
#define DID_JOB_LIST                400
#define DID_JOBNAME                 401
#define DID_QUEUE_NAME              240
