/* --------------------------------------------------------------------
                           Menu Header File
                              Chapter 5

                    Real World Programming for OS/2
             Copyright (c) 1993 Blain, Delimon, and English
-------------------------------------------------------------------- */

#define ID_APPNAME              1
#define IDS_WINDOWCOLOR         2
#define IDS_TEXTCOLOR           3

#define IDBMP_CHECK1           50
#define IDBMP_UNCHECK1         51
#define IDBMP_CHECK2           52
#define IDBMP_UNCHECK2         53
#define IDBMP_BMPITEM1         54
#define IDBMP_BMPITEM2         55
#define IDBMP_ODITEM1          56
#define IDBMP_ODITEM2          57
#define IDBMP_ODITEM3          58

#define COLOR_MENU            100   
#define IDC_COLOR             101

#define IDM_ALIGN             400
#define IDM_ALIGNLEFT         401
#define IDM_ALIGNCENTER       402
#define IDM_ALIGNRIGHT        403
#define IDM_ALIGNTOP          404
#define IDM_ALIGNMIDDLE       405
#define IDM_ALIGNBOTTOM       406

#define IDM_STYLE             500
#define IDM_STYLENORMAL       501
#define IDM_STYLEUNDERSCORE   502
#define IDM_STYLESTRIKEOUT    503

#define IDM_EDIT              600
#define IDM_UNDO              601
#define IDM_COPY              602
#define IDM_CUT               603
#define IDM_PASTE             604

#define IDM_ABOUT             700

#define BITMAP_MENU           800
#define IDM_BMPITEM1          801
#define IDM_BMPITEM2          802





