/* --------------------------------------------------------------------
                        LED Control Header File
                              Chapter 14

                    Real World Programming for OS/2
             Copyright (c) 1993 Blain, Delimon, and English
-------------------------------------------------------------------- */

/*************************************************
                    LED CONTROL
 ************************************************/

#define LEDCLASS   "LED"

/* Control registration function */
VOID RegisterLEDClass (HAB);
