/* --------------------------------------------------------------------
                         MiniMDI Header File
                              Chapter 3

                    Real World Programming for OS/2
             Copyright (c) 1993 Blain, Delimon, and English
-------------------------------------------------------------------- */

#define ID_APPNAME           1
#define IDD_TOOLBAR          2
#define IDD_WININFO          3

#define ID_CHILDWINDOW      11

#define IDPTR_HEART         20
#define IDPTR_CLIENT        21
#define IDPTR_SYSMENU       22
#define IDPTR_MENU          23
#define IDPTR_MINMAX        24
#define IDPTR_LEFT          25
#define IDPTR_TOP           26
#define IDPTR_LEFTTOP       27
#define IDPTR_RIGHTTOP      28
#define IDPTR_TITLEBAR      29
#define IDPTR_POPUPMENU     30

#define IDM_WINDOW         100
#define IDM_NEWCHILD       101
#define IDM_NEXTCHILD      102
#define IDM_CLOSEALL       103
#define IDM_ABOUT          104

#define IDM_ARRANGEMENU    110
#define IDM_TILE           111
#define IDM_CASCADE        112
#define IDM_ARRANGE        113

#define IDC_WININFO        200
#define IDC_RED            201
#define IDC_GREEN          202
#define IDC_BLUE           203
#define IDC_MOVE           204
#define IDC_TRACK          205
#define IDC_OPEN           206

#define IDC_TITLE          300
#define IDC_XPOS           301
#define IDC_YPOS           302
#define IDC_WIDTH          303
#define IDC_HEIGHT         304
#define IDC_STATE          305
                          
