/* --------------------------------------------------------------------
                         Chapter 7 Header File
                              Chapter 7

                    Real World Programming for OS/2
             Copyright (c) 1993 Blain, Delimon, and English
-------------------------------------------------------------------- */

/*  FONTMETRICS Dialog */

#define METRICS_DLG            2
#define DID_FAMILYNAME       100
#define DID_FACENAME         101  
#define DID_CODEPAGE         103
#define DID_POINT_SIZE       102
#define DID_EMHEIGHT         104
#define DID_XHEIGHT          105
#define DID_MAXASCENDER      106
#define DID_MAXDECENDER      107
#define DID_LOWERCASEASCENT  108
#define DID_LOWERCASEDECENT  109
#define DID_INTERNALLEADING  110
#define DID_EXTERNALLEADING  111
#define DID_AVECHARWIDTH     112
#define DID_MAXCHARWIDTH     113
#define DID_MAXCHARINC       114
#define DID_EMINC            115
#define DID_MAXBASELINEEXT   116
#define DID_WEIGHTCLASS      117
#define DID_WIDTHCLASS       118
#define DID_TYPE             119
#define DID_DEFINITION       120
#define DID_SELECTION        121
#define DID_CAPABILITIES     122
#define DID_KERNPAIRS        123
#define DID_FAMILYCLASS      124
#define DID_MATCH            125
#define DID_PANOSE           126
#define DID_FAMILYATOM       127
#define DID_FACEATOM         128


/* Shear and Rotation Dialog */

#define SHEAR_DLG              3
#define DID_CHAR_HEIGHT      500
#define DID_CHAR_WIDTH       501
#define DID_ANGLEX           502
#define DID_ANGLEY           503
#define DID_ROT_ANGLE        504
#define DID_SHEARX           505
#define DID_SHEARY           506
#define DID_SHEAR_ANGLE      507
#define DID_CHAR_EXTRA       508
#define DID_BREAK_EXTRA      509
#define DID_RESET_SIZE       510
#define DID_RESET_ANGLE      511
#define DID_RESET_SHEAR      512
#define DID_USER_TEXT        513
#define DID_DISPLAY_TEXT     514
#define DID_APPLY            515

#define FONT_LBOX            300
#define DID_POINTSIZE        5
