/* --------------------------------------------------------------------
                    Thread Information Header File
                              Chapter 15

                    Real World Programming for OS/2
             Copyright (c) 1993 Blain, Delimon, and English
-------------------------------------------------------------------- */

/* Exported Function */
MRESULT EXPENTRY PIBTIBDlgProc  (HWND,ULONG,MPARAM,MPARAM);

/* PIBTIB Dialog Controls             */

#define IDC_PID                      200
#define IDC_PPID                     201
#define IDC_MODULEHANDLE             202
#define IDC_STATUS                   203
#define IDC_TYPE                     204
#define IDC_COMMANDLINE              205
#define IDC_ENVIRONMENT              206
#define IDC_TID                      207
#define IDC_PRIORITY                 208
#define IDC_SLOT                     209
#define IDC_STACKBASE                210
#define IDC_STACKEND                 211

