/* --------------------------------------------------------------------
                          APPSAMP Header File
                              Chapter 10

                    Real World Programming for OS/2
             Copyright (c) 1993 Blain, Delimon, and English
-------------------------------------------------------------------- */

#define ID_APPNAME 1

#define IDM_COLOR  100
#define IDM_RED    101
#define IDM_GREEN  102
#define IDM_BLUE   103

#define IDM_CENTER 200

#define IDM_ABOUT  300

