/* --------------------------------------------------------------------
                           About Header File

                    Real World Programming for OS/2
             Copyright (c) 1993 Blain, Delimon, and English
-------------------------------------------------------------------- */

VOID DisplayAbout (HWND,PSZ);

/* Exported Function */
MRESULT EXPENTRY AboutDlgProc  (HWND,ULONG,MPARAM,MPARAM);

