/* --------------------------------------------------------------------
                          Thermo Header File
                              Chapter 10

                    Real World Programming for OS/2
             Copyright (c) 1993 Blain, Delimon, and English
-------------------------------------------------------------------- */

#define ID_APPNAME              1

#define IDC_BEVEL1             50
#define IDC_BEVEL2             51
#define IDC_BEVEL3             52
#define IDC_BEVEL4             53

#define IDC_PRIVATEALLOC      100
#define IDC_PRIVATESUBALLOC   101
#define IDC_PRIVATELIST       102
#define IDC_SHAREDALLOC       103
#define IDC_SHAREDSUBALLOC    104
#define IDC_SHAREDLIST        105
#define IDC_THERMOCOLOR       106
#define IDC_THERMOMETER       107

#define IDB_PRIVATEALLOC      200
#define IDB_PRIVATEFREE       201
#define IDB_PRIVATEFREEALL    202
#define IDB_SHAREDALLOC       203
#define IDB_SHAREDFREE        204
#define IDB_SHAREDFREEALL     205

#define IDM_ABOUT             300

