/* --------------------------------------------------------------------
                        Miscellaneous Header File
                              Chapter 15

                    Real World Programming for OS/2
             Copyright (c) 1993 Blain, Delimon, and English
-------------------------------------------------------------------- */

/* Dialog and Control Identifiers     */

#define ID_APPNAME                     1
#define IDD_PIBTIB                     2
#define IDD_DRIVES                     3
#define IDD_FILESEARCH                 4
#define IDD_SYSINFO                    5

#define IDM_SYSTEM                   100
#define IDM_PIBTIB                   101
#define IDM_SYSINFO                  102

#define IDM_FILES                    110
#define IDM_DRIVES                   111
#define IDM_FILESEARCH               112

#define IDM_ABOUT                    120
 
