/* --------------------------------------------------------------------
                    System Information Header File
                              Chapter 15

                    Real World Programming for OS/2
             Copyright (c) 1993 Blain, Delimon, and English
-------------------------------------------------------------------- */

/* Exported Function */
MRESULT EXPENTRY SysInfoDlgProc  (HWND,ULONG,MPARAM,MPARAM);

/* SysInfo Dialog Controls             */

#define IDC_SYSINFOLIST         500

