/* --------------------------------------------------------------------
                         MemMap Header File
                              Chapter 9

                    Real World Programming for OS/2
             Copyright (c) 1993 Blain, Delimon, and English
-------------------------------------------------------------------- */

#define ID_APPNAME         1

#define IDL_MEMLIST       10
#define IDB_REFRESH       11
#define IDT_PAGES         12
#define IDB_STARTADDRESS  13

#define IDM_ABOUT        100
