/* -------------------------------------------------------------------
                          Threads Header File
                              Chapter 12

                    Real World Programming for OS/2
             Copyright (c) 1993 Blain, Delimon, and English
------------------------------------------------------------------- */

/* Dialog and Control Identifiers     */

#define ID_APPNAME                     1
#define IDD_THREADDLG                  1
#define IDD_TIDDLG                     2
#define IDD_SORTINGDLG                 3

#define IDM_THREADS                  100
#define IDM_NEWTHREAD                101
#define IDM_NEWQMSGTHREAD            110
#define IDM_NEWSORTINGTHREAD         111
#define IDM_KILLALLTHREADS           102
#define IDM_ARRANGE                  103
#define IDM_ABOUT                    104

#define IDC_THREADID                 200
#define IDC_THREADPRIORITY           201
#define IDC_STATE                    202
#define IDC_CRITSECTION              203
#define IDC_SEMAPHORE                204
#define IDC_THERMOMETER              205
#define IDC_KILL                     206
#define IDC_UPPRIORITY               207
#define IDC_DOWNPRIORITY             208

#define IDC_PERCENT                  300
#define IDC_PERCENTBAR               301
#define IDC_SUSPEND                  302
#define IDC_RESUME                   303

